name: Build Psych Extended Online + Release
on:
  workflow_dispatch:
    inputs:
      setupCommand:
        description: 'Command to setup libraries (Standard: haxelib install hmm && haxelib run hmm install)'
        required: true
        default: 'haxelib install hmm && haxelib run hmm install'
      doCache:
        description: 'Enable build caching? (true/false)'
        required: true
        default: 'true'

permissions:
  contents: write
  discussions: write

env:
  PROJECT_NAME: PsychExtendedOnline

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android
            os: macos-15
            buildArgs: "android -final -D officialBuild"
            artifactName: androidBuild
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: iOS
            os: macos-15
            buildArgs: "ios -final -nosign -D officialBuild"
            artifactName: iOSBuild
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"

    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
      setupCommand: ${{ github.event.inputs.setupCommand }}
      doCache: ${{ github.event.inputs.doCache == 'true' }}

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
          name: androidBuild
          path: /home/runner

      - name: Move Android File
        run: mv /home/runner/*.apk /home/runner/${{ env.PROJECT_NAME }}-Android.apk || true

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
          name: iOSBuild
          path: /home/runner

      - name: Move iOS File
        run: mv /home/runner/*.ipa /home/runner/${{ env.PROJECT_NAME }}-iOS.ipa || true

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Latest Build"
          tag_name: "latest"
          prerelease: false
          files: |
            /home/runner/*.apk
            /home/runner/*.ipa
