name: Build Psych Extended Online + Release
on:
  workflow_dispatch:
    inputs:
      setupCommand:
        description: 'Setup Command'
        required: true
        default: 'haxelib install hmm && haxelib run hmm install'
      doCache:
        description: 'Enable Cache'
        required: true
        default: 'true'

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android
            os: ubuntu-latest
            buildArgs: "android -final"
            artifactName: androidBuild
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.3.6

      - name: Install Libraries
        run: |
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          ${{ github.event.inputs.setupCommand }}

      - name: Configure Android
        if: matrix.name == 'Android'
        run: |
          haxelib run lime setup android
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV

      - name: Build Game
        run: haxelib run lime build ${{ matrix.buildArgs }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifactName }}
          path: ${{ matrix.artifactPath }}

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: androidBuild
          path: ./output

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Mobile Port"
          tag_name: "latest"
          files: ./output/*.apk
