name: Build Psych Extended Online + Release
on:
  workflow_dispatch:
    inputs:
      setupCommand:
        description: 'Command to setup libraries'
        required: true
        default: 'haxelib install hmm && haxelib run hmm install'

permissions:
  contents: write

env:
  PROJECT_NAME: PsychExtendedOnline

jobs:
  build-android:
    name: Android Build
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Libraries
        run: |
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install hxCodec
          ${{ github.event.inputs.setupCommand }}

      - name: Configure Android Paths
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime setup android "${ANDROID_HOME}" "${ANDROID_NDK_LATEST_HOME}" "${JAVA_HOME_17_X64}"
        # This tells Lime exactly where the GitHub runner keeps the Android tools

      - name: Build Game
        run: haxelib run lime build android -final -D officialBuild

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk

  Releaser:
    needs: [build-android]
    runs-on: ubuntu-latest
    steps:
      - name: Download Build
        uses: actions/download-artifact@main
        with:
          name: androidBuild
          path: /home/runner

      - name: Move and Rename
        run: mv /home/runner/*.apk /home/runner/${{ env.PROJECT_NAME }}-Android.apk || true

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Mobile Build"
          tag_name: "latest"
          files: /home/runner/*.apk
